package app

import (
	"database/sql"
	"github.com/jinzhu/gorm"
	"time"
)

type Album struct {
	Id            int64
	Title         string
	Description   string
	AutoGenerated bool
	ParentAlbumId sql.NullInt64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Photos        []Photo `gorm:"many2many:album_photos;"`
}

func RootAlbums(database gorm.DB) []Album {
	var albums []Album
	database.Where("parent_album_id IS NULL").Find(&albums)
	return albums
}

func (album Album) children(database gorm.DB) []Album {
	var albums []Album
	database.Where("parent_album_id = ?", album.ParentAlbumId).Find(&albums)
	return albums
}

